
version: '3.8'

services:
  # Load Balancer Service
  loadbalancer:
    build:
      context: ./loadbalancer
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - account-service
      - product-service
      - transaction-service
    networks:
      - app-network
    environment:
      - ACCOUNT_SERVICE_URL=http://account-service:5001
      - PRODUCT_SERVICE_URL=http://product-service:5002
      - TRANSACTION_SERVICE_URL=http://transaction-service:5003

  # Account Service
  account-service:
    build:
      context: ./services/account-service
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - citus-master
    networks:
      - app-network
    environment:
      - PORT=5001
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=citus-master
      - DB_PORT=5432
      - DB_NAME=itemexchange
      - JWT_SECRET=your_jwt_secret_key_here

  # Product Service
  product-service:
    build:
      context: ./services/product-service
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    depends_on:
      - citus-master
    networks:
      - app-network
    environment:
      - PORT=5002
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=citus-master
      - DB_PORT=5432
      - DB_NAME=itemexchange
      - JWT_SECRET=your_jwt_secret_key_here

  # Transaction Service
  transaction-service:
    build:
      context: ./services/transaction-service
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    depends_on:
      - citus-master
    networks:
      - app-network
    environment:
      - PORT=5003
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=citus-master
      - DB_PORT=5432
      - DB_NAME=itemexchange
      - JWT_SECRET=your_jwt_secret_key_here

  # Citus Master Node
  citus-master:
    image: citusdata/citus:11.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=itemexchange
    volumes:
      - citus-master-data:/var/lib/postgresql/data
    networks:
      - app-network
    command: ["postgres", "-c", "max_connections=200"]

  # Citus Worker Nodes (for sharding)
  citus-worker-1:
    image: citusdata/citus:11.2
    depends_on:
      - citus-master
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - citus-worker-1-data:/var/lib/postgresql/data
    networks:
      - app-network
    command: ["postgres", "-c", "max_connections=100"]

  citus-worker-2:
    image: citusdata/citus:11.2
    depends_on:
      - citus-master
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - citus-worker-2-data:/var/lib/postgresql/data
    networks:
      - app-network
    command: ["postgres", "-c", "max_connections=100"]

  citus-worker-3:
    image: citusdata/citus:11.2
    depends_on:
      - citus-master
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - citus-worker-3-data:/var/lib/postgresql/data
    networks:
      - app-network
    command: ["postgres", "-c", "max_connections=100"]

  # Citus Worker Replicas
  citus-replica-1:
    image: citusdata/citus:11.2
    depends_on:
      - citus-worker-1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - citus-replica-1-data:/var/lib/postgresql/data
    networks:
      - app-network
    command: ["postgres", "-c", "max_connections=100", "-c", "hot_standby=on"]

  citus-replica-2:
    image: citusdata/citus:11.2
    depends_on:
      - citus-worker-2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - citus-replica-2-data:/var/lib/postgresql/data
    networks:
      - app-network
    command: ["postgres", "-c", "max_connections=100", "-c", "hot_standby=on"]

  citus-replica-3:
    image: citusdata/citus:11.2
    depends_on:
      - citus-worker-3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - citus-replica-3-data:/var/lib/postgresql/data
    networks:
      - app-network
    command: ["postgres", "-c", "max_connections=100", "-c", "hot_standby=on"]

  # Setup service to initialize Citus cluster
  citus-setup:
    image: citusdata/citus:11.2
    depends_on:
      - citus-master
      - citus-worker-1
      - citus-worker-2
      - citus-worker-3
      - citus-replica-1
      - citus-replica-2
      - citus-replica-3
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - app-network
    command: >
      bash -c "
        sleep 30 &&
        PGPASSWORD=postgres psql -h citus-master -U postgres -d itemexchange -c \"SELECT citus_add_node('citus-worker-1', 5432);\" &&
        PGPASSWORD=postgres psql -h citus-master -U postgres -d itemexchange -c \"SELECT citus_add_node('citus-worker-2', 5432);\" &&
        PGPASSWORD=postgres psql -h citus-master -U postgres -d itemexchange -c \"SELECT citus_add_node('citus-worker-3', 5432);\" &&
        PGPASSWORD=postgres psql -h citus-master -U postgres -d itemexchange -c \"SELECT citus_add_node('citus-replica-1', 5432, false);\" &&
        PGPASSWORD=postgres psql -h citus-master -U postgres -d itemexchange -c \"SELECT citus_add_node('citus-replica-2', 5432, false);\" &&
        PGPASSWORD=postgres psql -h citus-master -U postgres -d itemexchange -c \"SELECT citus_add_node('citus-replica-3', 5432, false);\" &&
        PGPASSWORD=postgres psql -h citus-master -U postgres -d itemexchange -f /docker-entrypoint-initdb.d/schema.sql
      "

networks:
  app-network:
    driver: bridge

volumes:
  citus-master-data:
  citus-worker-1-data:
  citus-worker-2-data:
  citus-worker-3-data:
  citus-replica-1-data:
  citus-replica-2-data:
  citus-replica-3-data:
